### ISSUE TITLE
Support escape sequences in the SRE parser

### ISSUE THREAD

**Issue by qw3ry** [qw3ry/SRE-DTMC-Transformations#1]
Support for `\e` (epsilon) and some other possibly useful escape sequences.

**Comment by lbeurerkellner** [comment]
👍

**Comment by qw3ry** [comment]
Fixed in 8c0a29fbcdd33083e7b908d7193980532db39058

I have not tested this new feature throughout, feel free to review the commit and/or submit a bug report if you find something wrong.

**Comment by lbeurerkellner** [comment]
I will have a look. Thank you!
